//
// Char.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Char: Codable {

    public var id: Int?
    public var name: String?
    public var status: String?
    public var species: String?
    public var type: String?
    public var gender: String?
    public var origin: CharOrigin?
    public var location: CharOrigin?
    public var image: String?
    public var url: String
    public var created: String?

    public init(id: Int? = nil, name: String? = nil, status: String? = nil, species: String? = nil, type: String? = nil, gender: String? = nil, origin: CharOrigin? = nil, location: CharOrigin? = nil, image: String? = nil, url: String, created: String? = nil) {
        self.id = id
        self.name = name
        self.status = status
        self.species = species
        self.type = type
        self.gender = gender
        self.origin = origin
        self.location = location
        self.image = image
        self.url = url
        self.created = created
    }

}
