//
// CharList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CharList: Codable {

    public var results: [Char]?

    public init(results: [Char]? = nil) {
        self.results = results
    }

}
