//
// CharOrigin.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CharOrigin: Codable {

    public var name: String?
    public var url: String?

    public init(name: String? = nil, url: String? = nil) {
        self.name = name
        self.url = url
    }

}
