//
// EpisodeList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct EpisodeList: Codable {

    public var results: [Episode]?

    public init(results: [Episode]? = nil) {
        self.results = results
    }

}
